### PR TITLE
Various build fixes

### PR DESCRIPTION
**Pull request by liyang**

### CODE REVIEW

**Comment by phonohawk** [comment]
Thank you very much for your patch. I'll soon release a new package.

**Comment by phonohawk** [comment]
Uploaded:
http://hackage.haskell.org/package/bitstream-0.2.0.4

**Comment by liyang** [comment]
Yay! Thank you!

I don't have a fix for the following warning unfortunately:
```
Data/Bitstream/Lazy.hs:692:1: Warning:
    Rule "Lazy Bitstream unstreamChunks/streamChunks fusion" may never fire
      because ‘unId’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘unId’
```
I tried the following patch, replacing `Id` with a local one so I could attach an `{-# INLINE[1] unId #-}` pragma:
```
diff --git a/Data/Bitstream.hs b/Data/Bitstream.hs
index b390101..d9a761a 100644
--- a/Data/Bitstream.hs
+++ b/Data/Bitstream.hs
@@ -177,7 +177,7 @@ import qualified Data.Vector.Storable as SV
 import qualified Data.Vector.Fusion.Stream as S
 import Data.Vector.Fusion.Stream.Monadic (Stream(..), Step(..))
 import Data.Vector.Fusion.Stream.Size
-import Data.Vector.Fusion.Util
+import Data.Vector.Fusion.Util hiding (Id (..))
 import Prelude ( Bool(..), Eq(..), Int, Integral, Maybe(..), Monad(..), Num(..)
                , Ord(..), Show(..), ($), error, fmap, fromIntegral, fst
                , otherwise
@@ -185,6 +185,9 @@ import Prelude ( Bool(..), Eq(..), Int, Integral, Maybe(..), Monad(..), Num(..)
 import Prelude.Unicode hiding ((⧺), (∈), (∉))
 import System.IO (FilePath, Handle, IO)
 
+newtype Id a = Id { unId :: a }
+{-# INLINE[1] unId #-}
+
 -- | A space-efficient representation of a 'Bool' vector, supporting
 -- many efficient operations. 'Bitstream's have an idea of
 -- /directions/ controlling how octets are interpreted as bits. There
```
but GHC then complains that:
```
Data/Bitstream.hs:189:15:
    The INLINE pragma for ‘unId’ lacks an accompanying binding
      (You cannot give a INLINE pragma for a record selector or class method)
```
It may be related to [GHC #7398](https://ghc.haskell.org/trac/ghc/ticket/7398), but honestly I'm not sure, and haven't investigated further.

I've got [another few commits](/liyang/bitstream/commits/master) that adds `attoparsec` support, if you don't mind a little module abstraction violation… (I'm waiting on bos/attoparsec#90, but even if @bos decides not to export the internals, I can still get what I need via [`true-name`](http://hackage.haskell.org/package/true-name).) I'm still working on it (will be force-pushing), and is probably best left for another (more major) release in any case.

**Comment by phonohawk** [comment]
> I don't have a fix for the following warning unfortunately

Hmm... I came up with the following workaround but I can't test it myself since I currently don't have any boxes with GHC 7.8.x installed:
```haskell
newtype Id a = Id a

unId ∷ Id a → a
{-# INLINE [1] unId #-}
unId (Id a) = a
```

> I've got another few commits that adds attoparsec support, if you don't mind a little module abstraction violation…

That looks very interesting but I'd prefer it to be a separate package, named something like ```attoparsec-bitstream```...

**Comment by liyang** [comment]
I tried that workaround too. Unfortunately one of the types from `Data.Vector.Fusion.Stream` refers to its own `Id`, so it's still problematic. :(

I'm not sure whether the "Rule ... may never fire" warning is actually valid or not--haven't had a chance to stare at and compare the core yet.

Sure thing, I'll wrap it up as a separate package. :)

**Pull request merged**
